import Link from "next/link";
import {dollars,suite,tools} from "@/lib/bim/catalog";
import Catalog from "./storefront";
export const dynamic="force-dynamic";
export default function BimHome() {
  const mode=process.env.BIM_PAYMENT_MODE==="live"?"live":"test";
  const available=Boolean(process.env.BIM_STRIPE_SECRET_KEY && process.env.BIM_STRIPE_PRICE_MAP && process.env.BIM_RELEASE_VERSION && (mode!=="live" || process.env.BIM_LIVE_APPROVED==="true"));
  return <main><div className="bim-status"><span/>{mode==="test"?"LAUNCH PREVIEW · TEST PAYMENTS ONLY":"BYGEORGE LAUNCH COLLECTION"}</div>
    <section className="bim-hero"><div className="bim-hero-copy"><p className="bim-eyebrow">LESS REPETITION. MORE REVIT.</p><h1>Your model.<br/>Your time.<br/><em>Back in your hands.</em></h1><p className="bim-lead">The everyday Revit jobs deserve better tools. Move data, coordinate views, and get sheets ready with a focused collection of pyRevit utilities.</p><div className="bim-hero-actions"><a href="#suite" className="bim-button">Explore the suite <span>↗</span></a><a href="#collection" className="bim-text-link">Find your next shortcut ↓</a></div><div className="bim-hero-meta"><span>WINDOWS + REVIT</span><span>POWERED BY PYREVIT</span><span>ONE-TIME LICENSE</span></div></div>
    <div className="bim-blueprint" aria-label="Illustrated Revit workflow: data, views, and sheets"><div className="bim-drawing-top"><span>BG / WORKFLOW STUDY</span><span>01 — 11</span></div><div className="bim-model"><div className="bim-model-floor floor-one"/><div className="bim-model-floor floor-two"/><div className="bim-model-floor floor-three"/><div className="bim-model-spine"/><span className="bim-model-point p-one"/><span className="bim-model-point p-two"/></div><div className="bim-floating-label label-data"><span>01</span><strong>Data, connected.</strong><small>Parameters → XLSX → Revit</small></div><div className="bim-floating-label label-views"><span>02</span><strong>Views, coordinated.</strong><small>Fewer repetitive steps.</small></div><div className="bim-drawing-bottom"><span>MODEL → DOCUMENT → DELIVER</span><span>BYGEORGE / BIM</span></div></div></section>
    <div className="bim-strip"><div><b>{suite.features.length}</b><span>tools in the launch collection</span></div><div><b>1</b><span>download for the whole suite</span></div><div><b>2</b><span>computers per license</span></div><div><b>0</b><span>subscription payments</span></div></div>
    <section className="bim-section" id="collection"><div className="bim-section-head"><div><p className="bim-eyebrow">A SMALLER TOOLBOX. A BETTER WORKDAY.</p><h2>Find the task.<br/><em>Skip the repetition.</em></h2></div><p>Choose one utility or get the collection. Every included tool uses the same download and activation key system.</p></div><Catalog available={available} mode={mode}/></section>
    <section className="bim-suite" id="suite"><div><p className="bim-eyebrow">ONE KEY. THE WHOLE LAUNCH COLLECTION.</p><h2>A little less clicking.<br/><em>Across your whole day.</em></h2><p>{suite.description}</p><ul><li>Data, family, view, and sheet workflows</li><li>One named user, up to two Windows computers</li><li>Perpetual use of the purchased version</li><li>Shared download with individual feature permissions</li></ul><p className="bim-compatibility">Target: Revit 2024–2026 + pyRevit IronPython. Compatibility testing is pending. Ghostly Transmission, Import Sheets, and both Copy Scope tools are deferred and excluded.</p></div><div className="bim-suite-price"><span>INTRODUCTORY SUITE PRICE</span><strong>{dollars(suite.price)}<small>USD</small></strong><p>One payment. No subscription.</p><Link href="/bim/products/launch-suite" className="bim-button">See suite & checkout ↗</Link><small>{tools.filter(t=>t.status==="candidate").length} tools · One download · Two activations</small></div></section>
    <section className="bim-section bim-get-started"><div><p className="bim-eyebrow">FROM DOWNLOAD TO RIBBON</p><h2>Three steps.<br/><em>Then back to work.</em></h2><Link href="/bim/install" className="bim-text-link">Read the installation guide ↗</Link></div><ol><li><span>01</span><div><h3>Check your setup</h3><p>Windows, a licensed copy of full Revit, and pyRevit with its IronPython engine. Revit LT is not supported.</p></div></li><li><span>02</span><div><h3>Install the collection</h3><p>Download your ZIP, extract it, and run Install-ByGeorge.ps1. Close Revit before installing.</p></div></li><li><span>03</span><div><h3>Activate your tools</h3><p>Open Revit, select a ByGeorge tool, and enter your key. An internet connection is required when launching a tool.</p></div></li></ol></section>
  </main>;
}
